version: '3'

services:
  metasploit:
    container_name: 'metasploit'
    image: "strm/metasploit"
    volumes:
      - ./config:/tmp/config

  medusa:
    build:
      context: ./docker/medusa/
    container_name: medusa
    volumes:
      - ./config:/tmp/config
